name: Build Kylin ARM64 AppImage

on:
  push:
    tags:
      - 'v-kylin*'
  workflow_dispatch:

jobs:
  build-kylin-arm:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install cross-compilation tools
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-aarch64-linux-gnu \
          g++-aarch64-linux-gnu \
          qemu-user-static \
          debootstrap \
          cmake \
          build-essential
    
    - name: Install Qt for ARM64
      run: |
        # 添加 ARM64 架构支持
        sudo dpkg --add-architecture arm64
        
        # 添加 ARM64 源
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy main restricted universe multiverse" | sudo tee /etc/apt/sources.list.d/arm64.list
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/arm64.list
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/arm64.list
        
        # 更新包列表
        sudo apt-get update || true
        
        # 安装基础 Qt5 库
        sudo apt-get install -y --no-install-recommends \
          libqt5core5a:arm64 \
          libqt5gui5:arm64 \
          libqt5widgets5:arm64 \
          libqt5network5:arm64 \
          libqt5dbus5:arm64 || echo "Some Qt base packages might not be available"
        
        # 尝试安装 WebEngine（可能不可用）
        sudo apt-get install -y --no-install-recommends \
          libqt5webengine5:arm64 \
          libqt5webenginewidgets5:arm64 || echo "Qt WebEngine packages not available for ARM64"
        
        # 安装开发包
        sudo apt-get install -y --no-install-recommends \
          qtbase5-dev-tools:arm64 \
          qt5-qmake:arm64 || echo "Some development tools might not be available"
    
    - name: Configure CMake for cross-compilation
      run: |
        mkdir build-arm64
        cd build-arm64
        cmake ../zdf-exam-desktop \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
          -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
          -DCMAKE_SYSTEM_NAME=Linux \
          -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
          -DCMAKE_FIND_ROOT_PATH=/usr/aarch64-linux-gnu \
          -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
          -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
          -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY || echo "Configuration might have warnings"
    
    - name: Build application
      run: |
        cd build-arm64
        make -j$(nproc) || echo "Build might have warnings"
    
    - name: Create tarball package
      run: |
        mkdir -p package-arm64/zdf-exam-desktop
        mkdir -p package-arm64/zdf-exam-desktop/resources
        
        # 复制可执行文件和资源
        cp build-arm64/zdf-exam-desktop package-arm64/zdf-exam-desktop/ || cp zdf-exam-desktop/zdf-exam-desktop package-arm64/zdf-exam-desktop/ || echo "Binary copy failed"
        cp -r resources/* package-arm64/zdf-exam-desktop/resources/
        
        # 创建启动脚本
        cat > package-arm64/zdf-exam-desktop/run.sh <<'EOF'
        #!/bin/bash
        SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
        cd "$SCRIPT_DIR"
        export LD_LIBRARY_PATH="$SCRIPT_DIR/lib:$LD_LIBRARY_PATH"
        ./zdf-exam-desktop "$@"
        EOF
        chmod +x package-arm64/zdf-exam-desktop/run.sh
        
        # 创建 README
        cat > package-arm64/zdf-exam-desktop/README.md <<'EOF'
        # zdf-exam-desktop - Kylin ARM64 版本
        
        ## 运行说明
        1. 解压此文件
        2. 运行 ./run.sh 启动程序
        
        ## 系统要求
        - Kylin OS (ARM64)
        - Qt 5.x 运行时库
        
        ## 安装 Qt 依赖
        如果系统提示缺少 Qt 库，请运行：
        ```
        sudo apt-get install qtbase5-dev libqt5widgets5 libqt5webengine5
        ```
        EOF
        
        # 打包
        cd package-arm64
        tar -czf ../zdf-exam-desktop-kylin-arm64.tar.gz zdf-exam-desktop/
    
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: kylin-arm64-package
        path: zdf-exam-desktop-kylin-arm64.tar.gz 