name: Build Kylin x86_64 AppImage

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-kylin-x86:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Configure APT for Ubuntu 22.04
      run: |
        # 创建 APT 配置以忽略 qt5-default 包
        echo 'Package: qt5-default' | sudo tee /etc/apt/preferences.d/ignore-qt5-default
        echo 'Pin: release *' | sudo tee -a /etc/apt/preferences.d/ignore-qt5-default
        echo 'Pin-Priority: -1' | sudo tee -a /etc/apt/preferences.d/ignore-qt5-default
        
        # 安装 qtchooser 并配置 Qt5
        sudo apt-get update
        sudo apt-get install -y qtchooser
        sudo update-alternatives --install /usr/bin/qmake qmake /usr/lib/qt5/bin/qmake 100 || true
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        # 设置 Qt5 环境变量，避免依赖 qt5-default
        export QT_SELECT=qt5
        sudo apt-get install -y \
          build-essential \
          cmake \
          qtbase5-dev \
          qtwebengine5-dev \
          libqt5websockets5-dev \
          libqt5webchannel5-dev \
          libqt5webengine5 \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libx11-dev \
          libxext-dev \
          libxfixes-dev \
          libxi-dev \
          libxrender-dev \
          libxcb1-dev \
          libxcb-glx0-dev \
          libxcb-keysyms1-dev \
          libxcb-image0-dev \
          libxcb-shm0-dev \
          libxcb-icccm4-dev \
          libxcb-sync0-dev \
          libxcb-xfixes0-dev \
          libxcb-shape0-dev \
          libxcb-randr0-dev \
          libxcb-render-util0-dev \
          libxkbcommon-dev \
          libxkbcommon-x11-dev \
          file
    
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        # 设置 Qt5 环境变量
        export QT_SELECT=qt5
        export Qt5_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5
        cmake ../zdf-exam-desktop -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake
    
    - name: Build application
      run: |
        cd build
        make -j$(nproc)
    
    - name: Prepare AppDir
      run: |
        mkdir -p AppDir/usr/bin
        mkdir -p AppDir/usr/share/applications
        mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
        mkdir -p AppDir/resources
        
        # 复制可执行文件
        cp build/zdf-exam-desktop AppDir/usr/bin/
        
        # 复制资源文件
        cp -r resources/* AppDir/resources/
        
        # 创建桌面文件
        cat > AppDir/usr/share/applications/zdf-exam-desktop.desktop <<EOF
        [Desktop Entry]
        Type=Application
        Name=zdf-exam-desktop
        Name[zh_CN]=zdf-exam-desktop
        Comment=教育考试场景专用安全浏览器
        Comment[zh_CN]=教育考试场景专用安全浏览器
        Exec=zdf-exam-desktop
        Icon=zdf-exam-desktop
        Categories=Education;Network;
        Terminal=false
        StartupNotify=true
        EOF
        
        # 创建配置文件说明
        cat > AppDir/README.md <<EOF
        # zdf-exam-desktop
        
        ## 配置说明
        首次运行时，程序会在同目录下创建 config.json 配置文件。
        您可以编辑此文件来修改：
        - url: 指向的网址
        - exitPassword: 退出密码
        - appName: 应用名称
        
        修改后重新启动程序即可生效。
        EOF
        
        # 复制图标（暂时使用 simple_icon.ico，后续可以转换为 PNG）
        cp resources/simple_icon.ico AppDir/usr/share/icons/hicolor/256x256/apps/zdf-exam-desktop.ico
    
    - name: Download linuxdeployqt
      run: |
        wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod +x linuxdeployqt-continuous-x86_64.AppImage
    
    - name: Create AppImage
      run: |
        # 设置环境变量，避免沙箱问题
        export APPIMAGE_EXTRACT_AND_RUN=1
        
        # 部署 Qt 依赖
        ./linuxdeployqt-continuous-x86_64.AppImage AppDir/usr/share/applications/*.desktop -appimage -no-translations -qmake=/usr/lib/qt5/bin/qmake
        
        # 重命名输出文件
        mv *.AppImage zdf-exam-desktop-kylin-x86_64.AppImage
    
    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        name: kylin-x86_64-appimage
        path: zdf-exam-desktop-kylin-x86_64.AppImage 