name: Build Windows Installer

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win32_msvc2019'
        modules: 'qtwebengine'
        set-env: true
        tools-only: false
    
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
    
    - name: Configure CMake
      shell: cmd
      run: |
        mkdir build
        cd build
        cmake ../zdf-exam-desktop -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release
    
    - name: Build application
      shell: cmd
      run: |
        cd build
        nmake
    
    - name: Deploy Qt dependencies
      shell: cmd
      run: |
        mkdir deploy
        copy build\zdf-exam-desktop.exe deploy\
        windeployqt --dir deploy --qmldir zdf-exam-desktop deploy\zdf-exam-desktop.exe
    
    - name: Copy resources
      shell: cmd
      run: |
        mkdir deploy\resources
        copy resources\*.* deploy\resources\
        echo Files in deploy directory:
        dir deploy /s
    
    - name: Create installer with NSIS
      shell: cmd
      run: |
        choco install nsis -y
        cd %GITHUB_WORKSPACE%
        dir resources
        mkdir Output
        echo === Checking installer.nsi content ===
        findstr /n "StrRep" installer.nsi || echo No StrRep found
        makensis -DARCH=x86 installer.nsi
    
    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: windows-installer
        path: Output\zdf-exam-desktop-setup-x86.exe 