name: Build Windows Installer

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.9.9'
        host: 'windows'
        target: 'desktop'
        arch: 'win32_msvc2015'
        modules: 'qtwebengine'
        set-env: true
        tools-only: false
    
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
        toolset: 14.0
    
    - name: Configure CMake
      shell: cmd
      run: |
        mkdir build
        cd build
        cmake ../zdf-exam-desktop -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release
    
    - name: Build application
      shell: cmd
      run: |
        cd build
        nmake
    
    - name: Deploy Qt dependencies
      shell: cmd
      run: |
        mkdir deploy
        copy build\zdf-exam-desktop.exe deploy\
        windeployqt --dir deploy --qmldir zdf-exam-desktop deploy\zdf-exam-desktop.exe
    
    - name: Copy resources
      shell: cmd
      run: |
        echo "正在复制资源文件..."
        mkdir deploy\resources
        echo "检查logo.ico是否存在："
        if exist resources\logo.ico (echo "logo.ico存在") else (echo "ERROR: logo.ico不存在!")
        copy resources\*.* deploy\resources\
        
        echo "验证资源文件复制结果："
        if exist deploy\resources\logo.ico (echo "logo.ico已成功复制") else (echo "ERROR: logo.ico复制失败!")
        
        echo "资源目录内容："
        dir resources /b
        
        echo "部署资源目录内容："
        dir deploy\resources /b
        
        echo "完整部署目录结构："
        dir deploy /s
    
    - name: Download VC++ Runtime
      shell: cmd
      run: |
        echo "下载VC++ 2015 Redistributable (x86)..."
        curl -L -o vcredist_x86.exe "https://aka.ms/vs/14/release/vc_redist.x86.exe"
        if exist vcredist_x86.exe (echo "VC++ Runtime下载成功") else (echo "ERROR: VC++ Runtime下载失败!")
    
    - name: Create installer with NSIS
      shell: cmd
      run: |
        choco install nsis -y
        cd %GITHUB_WORKSPACE%
        echo "NSIS安装脚本中的图标引用："
        findstr "MUI_ICON\|CreateShortcut" installer.nsi
        
        mkdir Output
        echo === Checking installer.nsi content ===
        findstr /n "StrRep" installer.nsi || echo No StrRep found
        makensis -DARCH=x86 installer.nsi
        
        echo "生成的安装包："
        dir Output
    
    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: windows-installer
        path: Output\智多分-机考桌面端-setup-x86.exe 